language: go

matrix:
  include:
    - go: 1.13.x
      env: VET=1 GO111MODULE=on
    - go: 1.13.x
      env: RACE=1 GO111MODULE=on
    - go: 1.13.x
      env: RUN386=1
    - go: 1.12.x
      env: GO111MODULE=on
    - go: 1.11.x
      env: GO111MODULE=on
    - go: stable

addons:
  apt:
    packages:
      - libsystemd-dev

env:
  global:
    GO111MODULE: on